// TODO TYPES

export const TODO_TYPES = {
    SET_TODO_LIST: "SET_TODO_LIST",
    OPEN_TODO_CREATE_MODAL: "OPEN_CREATE_TODO_MODAL",
    OPEN_TODO_UPDATE_MODAL: "OPEN_UPDATE_TODO_MODAL",
    CLOSE_TODO_MODAL: "CLOSE_TODO_MODAL",
    SET_ACTIVE_FILTER: "SET_ACTIVE_FILTER",
  };